### PR TITLE
Update to GNOME 40

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build
---
Let's try that again

**Comment by JerryCasiano** [comment]
Just fixed this in https://github.com/FontManager/font-manager/issues/208 

I'll tag a new release if you need me to. It's just one line...

**Comment by Eonfge** [comment]
@JerryCasiano  Ow, that would be great. If you can tag a new release, we can roll on.

I was going to look into it, but I'm a bit short on time the last couple of days. GNOME 40 couldn't have come at worse moment.

**Comment by JerryCasiano** [comment]
No problem.

I'll do it this evening.

Thanks.

**Comment by JerryCasiano** [comment]
Oh, I was about to tell you that I just created a new tag but I see it already built... I meant to do it last night but couldn't.

Anyway, thanks again!

**Comment by Eonfge** [comment]
No problem man, was already working on some other projects that need updates so when the mail came in, I was ready :smiley:

**Pull request merged**
