### PR TITLE
Update to GNOME 3.38

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
@JerryCasiano I've found a bug when using the later version of Valac
https://flathub.org/builds/#/builders/8/builds/3300/steps/6/logs/stdio
```
In file included from lib/vala/7a89c3f@@FontManager@sta/Utils.c:24:
lib/vala/7a89c3f@@FontManager@sta/Utils.c: In function ‘font_manager_show_version’:
lib/vala/FontManager-0.7.8.h:1092:33: error: ‘PACKAGE_NAME’ undeclared (first use in this function)
 1092 | #define FONT_MANAGER_ABOUT_NAME PACKAGE_NAME
      |                                 ^~~~~~~~~~~~
```

**Comment by JerryCasiano** [comment]
Well... That file doesn't even exist anymore.

Can you try a build from master for test purposes?

May have to tag a new release if master builds and runs.

**Comment by Eonfge** [comment]
@JerryCasiano different error:
```
valac -C --pkg libxml-2.0 --pkg sqlite3 --pkg pango --pkg gtk+-3.0 --pkg gobject-2.0 --pkg gmodule-2.0 --target-glib ' 2.62' --pkg glib-2.0 --pkg gio-unix-2.0 --pkg gio-2.0 --pkg json-glib-1.0 --color=always --directory src/font-manager/5842565@@font-manager@exe --basedir ../src/font-manager --gresources=../src/font-manager/font-manager-gresources.xml ../config.vapi lib/common/font-manager-common.vapi lib/unicode/Unicode-0.7.8.vapi ../src/font-manager/Aboiut.vala ../src/font-manager/Application.vala ../src/font-manager/ArchiveManager.vala ../src/font-manager/BaseTreeView.vala ../src/font-manager/Browse.vala ../src/font-manager/Cacheable.vala ../src/font-manager/Categories.vala ../src/font-manager/CellRenderer.vala ../src/font-manager/Collections.vala ../src/font-manager/Compare.vala ../src/font-manager/Controls.vala ../src/font-manager/Dialogs.vala ../src/font-manager/FontList.vala ../src/font-manager/Library.vala ../src/font-manager/MainWindow.vala ../src/font-manager/Migration.vala ../src/font-manager/Orthographies.vala ../src/font-manager/Orthography.vala ../src/font-manager/Sidebar.vala ../src/font-manager/TitleBar.vala ../src/font-manager/UserData.vala ../src/font-manager/Utils.vala ../src/font-manager/filters/Category.vala ../src/font-manager/filters/Collection.vala ../src/font-manager/filters/Disabled.vala ../src/font-manager/filters/FontListFilter.vala ../src/font-manager/filters/LanguageFilter.vala ../src/font-manager/filters/Unsorted.vala ../src/font-manager/filters/UserFonts.vala ../src/font-manager/preferences/Desktop.vala ../src/font-manager/preferences/Fontconfig.vala ../src/font-manager/preferences/Preferences.vala ../src/font-manager/preferences/UserActions.vala ../src/font-manager/preferences/UserInterface.vala ../src/font-manager/preferences/UserSources.vala
../src/font-manager/Application.vala:125.19-125.29: error: syntax error, no expression allowed between array brackets
            const string? [2] accels = {"<Ctrl>q", null };
                  ^^^^^^^^^^^
../src/font-manager/Application.vala:126.47-126.52: error: The name `accels' does not exist in the context of `FontManager.Application.startup'
            set_accels_for_action("app.quit", accels);
                                              ^^^^^^
../src/font-manager/TitleBar.vala:131.13-131.23: error: syntax error, no expression allowed between array brackets
            string? [2] accels = {"<Ctrl>%i".printf(i), null };
            ^^^^^^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
```

using master, d1055eefd46dde58c7abe7e7a6813627235c0617

**Comment by JerryCasiano** [comment]
Nice...

Alright, that's fixed in the latest commit. 

I'm finishing up on a couple things but will tag a new release this weekend.

**Comment by JerryCasiano** [comment]
@Eonfge 

I released 0.7.9 yesterday.

If you could update the Flatpak to point to that, that would be great.

**Comment by Eonfge** [comment]
I'm so sorry to say it, but you forgot to update the release date... :zipper_mouth_face: I've taken the liberty of using some sed-magic to get the appdata.xml into shape, so we don't have to go through the whole cycle again.

Thank you for being so fast in updating your package. This is really good teamwork

**Comment by JerryCasiano** [comment]
Ah, jeez. Thought I got em all.

Thanks for the reminder.

**Pull request merged**
