### PR TITLE
Enable networking to resolve #4

### LINKED ISSUE #4: Ver 0.80 Google fonts network offline
Installed version 0.80 on ubuntu 20.04 via flatpak, the Google Fonts integration does not work, it says "network offline" when, clearly the connection is working. Is it some kind of bug or am I missing something in the settings of the application?

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
@paulhewson could you possibly take a look and try this test version?

Edit. Never mind. Had a quick chat with upstream and I'll likely push 0.81 tonight

**Comment by paulhewson** [comment]
Still with 0.8.0, can't see 0.8.1 on flathub.
Anyway, I got an update yesterday but still 0.8.0. Now the networking problem seems to be gone but when trying to browse google fonts it complains about a missing gfc-date.json

**Comment by JerryCasiano** [comment]
@paulhewson 

The new release, actually releases... It's at 0.8.2 now.

Were done late in the evening yesterday so it'll probably get updated soon.

As far as your error goes, it's just a missing cache file. 

Two options, you can delete the cached json files or wait 24 hours for the next refresh. ;-)

I'm not sure where the Flatpak cache is so I don't want to give you the wrong info here.

In normal installations the cache is at ~/.cache/font-manager

**Comment by Eonfge** [comment]
They go in the XDG cache location. By defautlt, that would be:
`~/.var/app/org.gnome.FontManager/cache/font-manager`

**Comment by Eonfge** [comment]
Screenshot from 2020-12-03 16-41-48

I do actually have the same issue. How to reproduce:
- go  to the Google fonts
- select Most Popular from the dropdown

**Comment by JerryCasiano** [comment]
Can you post an `ls -la` from the cache directory?

**Comment by Eonfge** [comment]
```
font-manager
├── Fonts.sqlite
├── Fonts.sqlite-shm
├── Fonts.sqlite-wal
├── Metadata.sqlite
├── Metadata.sqlite-shm
├── Metadata.sqlite-wal
├── Orthography.sqlite
├── Orthography.sqlite-shm
└── Orthography.sqlite-wal
```

**Comment by JerryCasiano** [comment]
There are no results there... There should be 4 json files containing the responses received from Google fonts.

If there are any warning messages printed in the terminal when the application is run please post those.

Either way I'll have to take a look at this tonight.

**Comment by Eonfge** [comment]
Sadly not.I kept an eye on the terminal and I saw nothing special.

**Comment by JerryCasiano** [comment]
Did you run it from a shell inside the sandbox?

i.e.
```
flatpak run --command=sh --devel org.gnome.FontManager
/app/bin/font-manager
```
If not, see if there's any difference doing that.

**Comment by Eonfge** [comment]
```
[kevin@kevin-at-fedora ~]$ flatpak run --command=sh --devel org.gnome.FontManager
[kevin@kevin-at-fedora ~]$ /app/bin/font-manager
Gtk-Message: 18:33:46.289: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:33:46.289: Failed to load module "pk-gtk-module"
Gtk-Message: 18:33:46.290: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:33:46.290: Failed to load module "pk-gtk-module"
[font-manager]-Message: 18:33:46.319: ArchiveManager.vala:59: Install file-roller to enable archive support
```

You tell me, nothing special shows up.

**Comment by JerryCasiano** [comment]
Well. That sucks.

I'll have to figure out how to debug the Flatpak then.

Thanks for trying.

**Comment by JerryCasiano** [comment]
@Eonfge 

I tagged a new release which seems to fix this issue.

Hopefully this will be the last bump, at least for a little while.

Can you please test it and give it a thumbs up or down?

**Comment by Eonfge** [comment]
```
[kevin@kevin-at-fedora ~/Projects/org.gnome.FontManager]$ flatpak run org.gnome.FontManager 
Gtk-Message: 11:11:32.113: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:11:32.113: Failed to load module "pk-gtk-module"
Gtk-Message: 11:11:32.114: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:11:32.114: Failed to load module "pk-gtk-module"
[font-manager]-Message: 11:11:32.158: ArchiveManager.vala:59: Install file-roller to enable archive support
Gtk-Message: 11:11:38.316: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:11:38.316: Failed to load module "pk-gtk-module"
Gtk-Message: 11:11:38.316: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:11:38.316: Failed to load module "pk-gtk-module"

(font-manager:2): [font-manager]-WARNING **: 11:11:39.886: GoogleFonts.vala:164: Failed to download data for : gfc-date.json :: 2

(font-manager:2): [font-manager]-WARNING **: 11:11:39.886: GoogleFonts.vala:164: Failed to download data for : gfc-alpha.json :: 2

(font-manager:2): [font-manager]-WARNING **: 11:11:39.886: GoogleFonts.vala:164: Failed to download data for : gfc-date.json :: 2

(font-manager:2): [font-manager]-WARNING **: 11:11:39.886: GoogleFonts.vala:164: Failed to download data for : gfc-alpha.json :: 2

(font-manager:2): [font-manager]-WARNING **: 11:11:39.886: GoogleFonts.vala:164: Failed to download data for : gfc-date.json :: 2

(font-manager:2): GLib-ERROR **: 11:11:39.887: Creating pipes for GWakeup: Too many open files
```

Not sure why this is an issue. I haven't intentionally blocked Google-domains in my home network, but for some reason it can't connect well.

**Comment by paulhewson** [comment]
updated via flatpak to 0.8.3. Now Google Fonts browsing seems to work fine
Thank you

**Comment by JerryCasiano** [comment]
@paulhewson 

Good to hear.

@Eonfge 

Well, that's at least progress, I guess...

I think code 2 means or could resolve the host name, not positive I'll have to check.

Does it show you any details in the interface itself?

If not, I'll have to look into that.

I really want any errors in that area of the application to at least show a somewhat usable error message to the user.

**Pull request merged**
